Dashboard/urls.py
from django.conf.urls import url
from . import views

app_name = 'Dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login_user/$', views.login_user, name='login_user'),
    # url(r'^logout_user/$', views.logout_user, name='logout_user'),
    # url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    # url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    # url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^create_match/$', views.create_match, name='create_match'),
    url(r'^calculate_match/(?P<match_number>[0-9]+)/$', views.calculate_match, name='calculate_match'),
    # url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    # url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    # url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    # url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
]

LetsBet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Dashboard/', include('Dashboard.urls')),
    url(r'^', include('Dashboard.urls')),
]

Dashboard/models.py
from django.db import models
from django.utils.timezone import now

class overall_status(models.Model):
    date = models.DateTimeField(default=now)
    akash = models.IntegerField(primary_key=True)
    ayush = models.IntegerField()
    ronak = models.IntegerField()
    raghav = models.IntegerField()
    house = models.IntegerField()

    def __str__(self):
        return str(self.akash) + '#' + str(self.ayush) + '#' + str(self.ronak) + '#' + str(self.raghav) +'#'+ str(self.house)


class match_status(models.Model):
    date = models.DateTimeField(default=now)
    match_number = models.IntegerField(primary_key=True)
    match_teams = models.TextField(default="")
    akash = models.TextField()
    ayush = models.TextField()
    ronak = models.TextField()
    raghav = models.TextField()
    isCalculated = models.BooleanField(default=False)

    def __str__(self):
        return str(self.match_number)+ '-'+ str(self.akash) + '-' + str(self.ayush) + '-' + str(self.ronak) + '-' + str(self.raghav) + '-' + str(self.isCalculated)

Dashboard/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import overall_status, match_status
from django.http import HttpResponseRedirect



def create_match(request):
    if request.method == "POST":
        try:
            match_number = request.POST.get('match_number')

            match_team_1 = request.POST.get('team_1')
            match_team_2 = request.POST.get('team_2')

            batsman_11 = request.POST.get('batsman_11')
            batsman_21 = request.POST.get('batsman_21')
            allrounder1 = request.POST.get('all_rounder1')
            bowler_11 = request.POST.get('bowler_11')
            bowler_21 = request.POST.get('bowler_21')

            batsman_12 = request.POST.get('batsman_12')
            batsman_22 = request.POST.get('batsman_22')
            allrounder2 = request.POST.get('all_rounder2')
            bowler_12 = request.POST.get('bowler_12')
            bowler_22 = request.POST.get('bowler_22')

            batsman_13 = request.POST.get('batsman_13')
            batsman_23 = request.POST.get('batsman_23')
            allrounder3 = request.POST.get('all_rounder3')
            bowler_13 = request.POST.get('bowler_13')
            bowler_23 = request.POST.get('bowler_23')

            batsman_14 = request.POST.get('batsman_14')
            batsman_24 = request.POST.get('batsman_24')
            allrounder4 = request.POST.get('all_rounder4')
            bowler_14 = request.POST.get('bowler_14')
            bowler_24 = request.POST.get('bowler_24')

            akash_bet = str(batsman_11) + ',' + str(batsman_21) + ',' + str(allrounder1) + ','+ str(bowler_11) + ','+ str(bowler_21)
            ayush_bet = str(batsman_12) + ',' + str(batsman_22) + ',' + str(allrounder2) + ','+ str(bowler_12) + ','+ str(bowler_22)
            ronak_bet = str(batsman_13) + ',' + str(batsman_23) + ',' + str(allrounder3) + ','+ str(bowler_13) + ','+ str(bowler_23)
            raghav_bet = str(batsman_14) + ',' + str(batsman_24) + ',' + str(allrounder4) + ','+ str(bowler_14) + ','+ str(bowler_24)

            match_teams = str(match_team_1)+ '-' + str(match_team_2)

            match_object = match_status(match_number = match_number, match_teams = match_teams ,akash = akash_bet, ayush = ayush_bet, ronak = ronak_bet,
                                        raghav = raghav_bet)
            match_object.save()

            return HttpResponseRedirect("%s" % ("/Dashboard/index"))

        except ValueError:
            messages.error(request, 'Match number must be numeric', fail_silently=True)
            return HttpResponseRedirect("%s" % ("/Dashboard/create_match"))
        except :
            messages.error(request, 'Can\'t be left blank', fail_silently=True)
            return HttpResponseRedirect("%s" % ("/Dashboard/create_match"))


    else:
        return render(request,'Dashboard/create.html',{})


def index(request):
    try:
        player_status = overall_status.objects.order_by('-date')[0]
    except IndexError:
        player_status_obj = overall_status(akash=0, ayush=0, ronak=0, raghav=0, house=0)
        player_status_obj.save()
        player_status = overall_status.objects.order_by('-date')[0]
    all_match_status = match_status.objects.all().order_by('-date')
    return render(request, 'Dashboard/index.html',{'player_status': player_status, 'all_match_status': all_match_status})


def calculate_match(request, match_number):
    if request.method == "POST":
        try:
            match_number = request.POST.get('match_number')

            is_cal = request.POST.get('is_cal')

            batsman_11 = request.POST.get('batsman_11')
            batsman_21 = request.POST.get('batsman_21')
            allrounder1_r = request.POST.get('all_rounder1_r')
            allrounder1_w = request.POST.get('all_rounder1_w')
            bowler_11 = request.POST.get('bowler_11')
            bowler_21 = request.POST.get('bowler_21')

            batsman_12 = request.POST.get('batsman_12')
            batsman_22 = request.POST.get('batsman_22')
            allrounder2_r = request.POST.get('all_rounder2_r')
            allrounder2_w = request.POST.get('all_rounder2_w')
            bowler_12 = request.POST.get('bowler_12')
            bowler_22 = request.POST.get('bowler_22')

            batsman_13 = request.POST.get('batsman_13')
            batsman_23 = request.POST.get('batsman_23')
            allrounder3_r = request.POST.get('all_rounder3_r')
            allrounder3_w = request.POST.get('all_rounder3_w')
            bowler_13 = request.POST.get('bowler_13')
            bowler_23 = request.POST.get('bowler_23')

            batsman_14 = request.POST.get('batsman_14')
            batsman_24 = request.POST.get('batsman_24')
            allrounder4_r = request.POST.get('all_rounder4_r')
            allrounder4_w = request.POST.get('all_rounder4_w')
            bowler_14 = request.POST.get('bowler_14')
            bowler_24 = request.POST.get('bowler_24')

            akash_points = 1*int(batsman_11) + 1*int(batsman_21) + 1*int(allrounder1_r) + 10*int(allrounder1_w) + 20*int(bowler_11) + 20*int(bowler_21)
            ayush_points = 1*int(batsman_12) + 1*int(batsman_22) + 1*int(allrounder2_r) + 10*int(allrounder2_w) + 20*int(bowler_12) + 20*int(bowler_22)
            ronak_points = 1*int(batsman_13) + 1*int(batsman_23) + 1*int(allrounder3_r) + 10*int(allrounder3_w) + 20*int(bowler_13) + 20*int(bowler_23)
            raghav_points = 1*int(batsman_14) + 1*int(batsman_24) + 1*int(allrounder4_r) + 10*int(allrounder4_w) + 20*int(bowler_14) + 20*int(bowler_24)

            is_cal = False

            player_score_dict = {
                'akash' : akash_points,
                'ayush': ayush_points,
                'ronak': ronak_points,
                'raghav': raghav_points
            }

            print(player_score_dict)

            player_score_list = [akash_points, ayush_points, ronak_points, raghav_points]
            player_name_list = ["akash_points", "ayush_points", "ronak_points", "raghav_points"]

            print(player_score_list)
            print(set(player_score_list))
            #check for all different
            if ((akash_points == ayush_points) and (ronak_points == raghav_points)):
                if (akash_points > ronak_points):
                    previous = overall_status.objects.order_by('-date')[0]
                    overall_status_obj = overall_status(akash=(int(30) + int(str(previous).split('#')[0])),
                                                        ayush=(int(30) + int(str(previous).split('#')[1])),
                                                        ronak=(int(-40) + int(str(previous).split('#')[2])),
                                                        raghav=(int(-40) + int(str(previous).split('#')[3])),
                                                        house=(20 + int(str(previous).split('#')[4])))

                    overall_status_obj.save()
                else:
                    previous = overall_status.objects.order_by('-date')[0]
                    overall_status_obj = overall_status(akash=(int(-40) + int(str(previous).split('#')[0])),
                                                        ayush=(int(-40) + int(str(previous).split('#')[1])),
                                                        ronak=(int(30) + int(str(previous).split('#')[2])),
                                                        raghav=(int(30) + int(str(previous).split('#')[3])),
                                                        house=(20 + int(str(previous).split('#')[4])))

                    overall_status_obj.save()
                match_status.objects.filter(match_number=match_number).update(isCalculated=True)

            elif ((akash_points == ronak_points) and (ayush_points == raghav_points)):
                if (akash_points > ayush_points):
                    previous = overall_status.objects.order_by('-date')[0]
                    overall_status_obj = overall_status(akash=(int(30) + int(str(previous).split('#')[0])),
                                                        ayush=(int(-40) + int(str(previous).split('#')[1])),
                                                        ronak=(int(30) + int(str(previous).split('#')[2])),
                                                        raghav=(int(-40) + int(str(previous).split('#')[3])),
                                                        house=(20 + int(str(previous).split('#')[4])))

                    overall_status_obj.save()
                else:
                    previous = overall_status.objects.order_by('-date')[0]
                    overall_status_obj = overall_status(akash=(int(-40) + int(str(previous).split('#')[0])),
                                                        ayush=(int(30) + int(str(previous).split('#')[1])),
                                                        ronak=(int(-40) + int(str(previous).split('#')[2])),
                                                        raghav=(int(30) + int(str(previous).split('#')[3])),
                                                        house=(20 + int(str(previous).split('#')[4])))

                    overall_status_obj.save()
                match_status.objects.filter(match_number=match_number).update(isCalculated=True)

            elif ((akash_points == raghav_points) and (ayush_points == ronak_points)):
                if (akash_points > ayush_points):
                    previous = overall_status.objects.order_by('-date')[0]
                    overall_status_obj = overall_status(akash=(int(30) + int(str(previous).split('#')[0])),
                                                        ayush=(int(-40) + int(str(previous).split('#')[1])),
                                                        ronak=(int(-40) + int(str(previous).split('#')[2])),
                                                        raghav=(int(30) + int(str(previous).split('#')[3])),

Dashboard/templates/Dashboard/calculate_match.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bet Calculation</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'Dashboard/calculate.css'%}">
</head>
<body>
    <h1 class="calc-h1">Lets Bet: Calculation Arena</h1>
    <h2 class="match-num">Match Number: {{match_number}} </h2>
    {% if is_cal == "False" %}

    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if messages %}
            <p class="msg">
                {% for message in messages %}
                    <b><i>*{{ message }}</i></b>
                {% endfor %}
            </p>
        {% endif %}
        <div class="data-container container">
             <div class="col-lg-3 col-md-6 col-sm-6 group">
                <p><b>Player Name: {{total_list.0.player_name}}</b></p>
                <p><label for="batsman_11">{{total_list.0.1}} runs : </label><input name="batsman_11" value="" id="batsman_11"></p>
                <p><label for="batsman_21">{{total_list.0.2}} runs : </label><input name="batsman_21" value="" id="batsman_21"></p>
                <p><label for="all_rounder1_r">{{total_list.0.3}} runs: </label><input name="all_rounder1_r" value="" id="all_rounder1_r"></p>
                <p><label for="all_rounder1_w">{{total_list.0.3}} wicket: </label><input name="all_rounder1_w" value="" id="all_rounder1_w"></p>
                <p><label for="bowler_11">{{total_list.0.4}} wicket: </label><input name="bowler_11" value="" id="bowler_11"></p>
                <p><label for="bowler_21">{{total_list.0.5}} wicket: </label><input name="bowler_21" value="" id="bowler_21"></p>

            </div>

            <div class="col-lg-3 col-md-6 col-sm-6 group">
                <p><b>Player Name: {{total_list.1.player_name}}</b></p>
                <p><label for="batsman_12">{{total_list.1.1}} runs: </label><input name="batsman_12" value="" id="batsman_12"></p>
                <p><label for="batsman_22">{{total_list.1.2}} runs: </label><input name="batsman_22" value="" id="batsman_22"></p>
                <p><label for="all_rounder2_r">{{total_list.1.3}} runs: </label><input name="all_rounder2_r" value="" id="all_rounder2_r"></p>
                <p><label for="all_rounder2_w">{{total_list.1.3}} wicket: </label><input name="all_rounder2_w" value="" id="all_rounder2_w"></p>
                <p><label for="bowler_12">{{total_list.1.4}} wicket: </label><input name="bowler_12" value="" id="bowler_12"></p>
                <p><label for="bowler_22">{{total_list.1.5}} wicket: </label><input name="bowler_22" value="" id="bowler_22"></p>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6 group">

                <p><b>Player Name: {{total_list.2.player_name}}</b></p>
                <p><label for="batsman_13">{{total_list.2.1}} runs: </label><input name="batsman_13" value="" id="batsman_13"></p>
                <p><label for="batsman_23">{{total_list.2.2}} runs: </label><input name="batsman_23" value="" id="batsman_23"></p>
                <p><label for="all_rounder3_r">{{total_list.2.3}} runs: </label><input name="all_rounder3_r" value="" id="all_rounder3_r"></p>
                <p><label for="all_rounder3_w">{{total_list.2.3}} wicket: </label><input name="all_rounder3_w" value="" id="all_rounder3_w"></p>
                <p><label for="bowler_13">{{total_list.2.4}} wicket: </label><input name="bowler_13" value="" id="bowler_13"></p>
                <p><label for="bowler_23">{{total_list.2.5}} wicket: </label><input name="bowler_23" value="" id="bowler_23"></p>
            </div>

            <div class="col-lg-3 col-md-6 col-sm-6 group">
                <p><b>Player Name: {{total_list.3.player_name}}</b></p>
                <p><label for="batsman_14">{{total_list.3.1}} runs: </label><input name="batsman_14" value="" id="batsman_14"></p>
                <p><label for="batsman_24">{{total_list.3.2}} runs: </label><input name="batsman_24" value="" id="batsman_24"></p>
                <p><label for="all_rounder4_r">{{total_list.3.3}} runs: </label><input name="all_rounder4_r" value="" id="all_rounder4_r"></p>
                <p><label for="all_rounder4_w">{{total_list.3.3}} wicket: </label><input name="all_rounder4_w" value="" id="all_rounder4_w"></p>
                <p><label for="bowler_14">{{total_list.3.4}} wicket: </label><input name="bowler_14" value="" id="bowler_14"></p>
                <p><label for="bowler_24">{{total_list.3.5}} wicket: </label><input name="bowler_24" value="" id="bowler_24"></p>
            </div>
        </div>

        <input name="match_number" value="{{match_number}}" type="hidden">
        <input name="is_cal" value="{{is_cal}}" type="hidden">
        <button class="submit-btn">Submit</button>
    </form>


{% else %}
    *bet has been calculated
    <a href="{% url 'Dashboard:index' %}">
        <button type="button" class="calc-btn">Back to index</button>
    </a>
{% endif %}

</body>
</html>

Dashboard/templates/Dashboard/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create a Bet</title>
</head>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'Dashboard/create.css'%}">
<body>

  <h1 class="create-h1">Room-303</h1>

  <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        <div class="match-info row col-md-12 col-sm-12">
          {% csrf_token %}
            {% if messages %}
                <p>
                    {% for message in messages %}
                        <b><i>*{{ message }}</i></b>
                    {% endfor %}
                </p>
            {% endif %}
          <div class="row">
            <label for="matchNumber">Match Number :</label>
            <input id="matchNumber" type="text" name="match_number" value="" maxlength="100" placeholder="Eg. 22" />
          </div>
          <div class="row select-teams">Select Teams:
            <select name="team_1">
              <option value="RCB">RCB</option>
              <option value="MI">MI</option>
              <option value="SRH">SRH</option>
              <option value="KXIP">KXIP</option>
              <option value="DD">DD</option>
              <option value="PSG">PSG</option>
              <option value="GL">GL</option>
              <option value="KKR">KKR</option>
            </select>&nbsp;&nbsp; vs &nbsp;&nbsp;
            <select name="team_2">
             <option value="RCB">RCB</option>
              <option value="MI">MI</option>
              <option value="SRH">SRH</option>
              <option value="KXIP">KXIP</option>
              <option value="DD">DD</option>
              <option value="PSG">PSG</option>
              <option value="GL">GL</option>
              <option value="KKR">KKR</option>
            </select>
          </div>
        </div>
        <div class="data col-sm-12 col-md-12">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Player</th>
                <th>Batsman 1</th>
                <th>Batsman 2</th>
                <th>All rounder</th>
                <th>Bowler 1</th>
                <th>Bowler 2</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Akash</td>
                <td><input type="text" name="batsman_11" value="" maxlength="100" placeholder="Sachin"  /></td>
                <td><input type="text" name="batsman_21" value="" maxlength="100" placeholder="Sehwag" /></td>
                <td><input type="text" name="all_rounder1" value="" maxlength="100" placeholder="Irfan" /></td>
                <td><input type="text" name="bowler_11" value="" maxlength="100" placeholder="Nehra" /></td>
                <td><input type="text" name="bowler_21" value="" maxlength="100" placeholder="Goni" /></td>
              </tr>
              <tr>
                <td>Ayush</td>
                <td><input type="text" name="batsman_12" value="" maxlength="100" placeholder="Sachin" /></td>
                <td><input type="text" name="batsman_22" value="" maxlength="100" placeholder="Sehwag" /></td>
                <td><input type="text" name="all_rounder2" value="" maxlength="100" placeholder="Irfan" /></td>
                <td><input type="text" name="bowler_12" value="" maxlength="100" placeholder="Nehra" /></td>
                <td><input type="text" name="bowler_22" value="" maxlength="100" placeholder="Goni" /></td>
              </tr>
              <tr>
                <td>Ronak</td>
                <td><input type="text" name="batsman_13" value="" maxlength="100" placeholder="Sachin" /></td>
                <td><input type="text" name="batsman_23" value="" maxlength="100" placeholder="Sehwag" /></td>
                <td><input type="text" name="all_rounder3" value="" maxlength="100" placeholder="Irfan" /></td>
                <td><input type="text" name="bowler_13" value="" maxlength="100" placeholder="Nehra" /></td>
                <td><input type="text" name="bowler_23" value="" maxlength="100" placeholder="Goni" /></td>
              </tr>
              <tr>
                <td>Raghav</td>
                <td><input type="text" name="batsman_14" value="" maxlength="100" placeholder="Sachin" /></td>
                <td><input type="text" name="batsman_24" value="" maxlength="100" placeholder="Sehwag" /></td>
                <td><input type="text" name="all_rounder4" value="" maxlength="100" placeholder="Irfan" /></td>
                <td><input type="text" name="bowler_14" value="" maxlength="100" placeholder="Nehra" /></td>
                <td><input type="text" name="bowler_24" value="" maxlength="100" placeholder="Goni" /></td>
              </tr>
            </tbody>
        </table>
        </div>
        <br>
        <br>

        <button class="create">Submit</button>
  </form>
</body>

</html>

Dashboard/templates/Dashboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'Dashboard/index.css'%}">
<body>
<h1 class="index-h1">Lets Bet: The Season of IPL</h1>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
            <li data-target="#myCarousel" data-slide-to="5"></li>
            <li data-target="#myCarousel" data-slide-to="6"></li>
            <li data-target="#myCarousel" data-slide-to="7"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <figure class="img-rcb gallery-img"></figure>
            </div>

            <div class="item">
              <figure class="img-dd gallery-img"></figure>
            </div>

            <div class="item">
              <figure class="img-kkr gallery-img"></figure>
            </div>

            <div class="item">
              <figure class="img-kxip gallery-img"></figure>
            </div>

            <div class="item">
              <figure class="img-rps gallery-img"></figure>
            </div>

            <div class="item">
              <figure class="img-srh gallery-img"></figure>
            </div>

            <div class="item">
              <figure class="img-mi gallery-img"></figure>
            </div>

            <div class="item">
              <figure class="img-gl gallery-img"></figure>
            </div>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
      </div>
<!-- <h2>Longest Dick</h2> -->
<h2 class="status-heading">Player Status</h2>
<div class="status-info">
    <p>Akash:  {{player_status.akash}}</p>
    <p>Ayush:  {{player_status.ayush}}</p>
    <p>Ronak:  {{player_status.ronak}}</p>
    <p>Raghav: {{player_status.raghav}}</p>
    <p>House:  {{player_status.house}}</p>
    <p>Date: {{player_status.date}}</p>
</div>

<h3>Match Wise Stripping</h3>
<div class="full-status">{% for status in all_match_status %}
        <ul>
        <h4>Match Number: &nbsp; {{status.match_number}}</h4>
        <h4>Match Teams:  &nbsp; {{status.match_teams}}</h4>
        <li>Akash Players: &nbsp; {{status.akash}}</li>
        <li>Ayush Players:  &nbsp; {{status.ayush}}</li>
        <li>Ronak Players:  &nbsp; {{status.ronak}}</li>
        <li>Raghav Players:  &nbsp; {{status.raghav}}</li>
        <li>Date Created:  &nbsp; {{status.date}}</li>
        <li><a href="{% url 'Dashboard:calculate_match' status.match_number %}">Calculate Match</a></li>
        </ul>
    {% endfor%}
</div>
<a href="{% url 'Dashboard:create_match' %}">
    <button type="button" class="index">Start a Bet</button>
</a>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</html>